### PR TITLE
Completed the todo to generate the icon font without icomoon.

### PR DESCRIPTION
**Pull request by joelpittet**
- Added node/gulp.
- Replaced eot with woff2 as that should be better going forward and faster.
- Added sample preview HTML generation to see the icons in action.
- Addes SASS boilerplate icon generation.

### CODE REVIEW

**Comment by joelpittet** [comment]
Only one buggered icon: libricons

**Comment by joelpittet** [comment]
Fixed the pencil by making it larger. We could probably do the same for all of them to ensure their quality when converted to fonts.  I'd suggest 1000px instead of 15px.
I normalized them in the gulp file but it's nice when they all start that size.

**Comment by joelpittet** [comment]
I'd like to match up the numerical codes in the SVG file name some how but I'm not sure the correlation between those and the unicode characters?

**Comment by ry5n** [comment]
@joelpittet This looks good. It’s been a long time since I worked on this though, so I’m not 100% confident evaluating it. Any chance yourself or someone else in the Drupal community would like to take over maintenance of the project?

**Comment by joelpittet** [comment]
I'd be happy to take it over until someone else wants to.  How do I go about doing that?

**Comment by ry5n** [comment]
I can transfer ownership easily, but not if you already have a fork of the repo. For the moment, I’ve added you as a contributor.

**Comment by ry5n** [comment]
Now that you’ve merged this, if you delete your fork, I can transfer ownership. Just let me know!

**Comment by joelpittet** [comment]
Thanks @ry5n Yeah only did this because I saw the TODO and had the tools laying around and wondered if they still worked:) Fun project!

**Comment by ry5n** [comment]
:)

**Comment by joelpittet** [comment]
Deleted, if you want to keep it I can just dev and push here if you prefer.

**Pull request merged**
